import React, { useState } from 'react';
import Layout from '../../../layouts/Layout';
import { PageTitle, StatCards, Card, Btn, Badge, SearchBar, Table, Avatar } from '../../../components/Shared';
import { PAYROLL, BIOMETRIC } from '../../../lib/mock2';
import { BadgeDollarSign, Users, Wallet, TrendingUp, Download, Fingerprint, CheckCircle2, XCircle, Clock, UserPlus, CalendarDays, ReceiptIndianRupee, HeartHandshake, Target, BriefcaseBusiness, ShieldCheck, FileText, ChevronRight, AlertTriangle, UserCheck, Building2, Banknote, Search, Plus, X, Upload, IndianRupee, Award, GraduationCap, ClipboardCheck, Settings2 } from 'lucide-react';
import { filterRows, downloadCSV } from '../../../utils';
import { LiquidPills } from '../../../motion/LiquidTabs';

export const HRPayroll = () => {
  const [tab, setTab] = useState('overview');
  const [q, setQ] = useState('');
  const [payroll, setPayroll] = useState(PAYROLL);
  const [message, setMessage] = useState('');
  const [showEmployee, setShowEmployee] = useState(false);
  const [showPayroll, setShowPayroll] = useState(false);
  const [month, setMonth] = useState('August 2026');
  const [employees, setEmployees] = useState([
    { id:'TCH-1024', name:'Ananya Rao', role:'Senior English Teacher', department:'Academics', type:'Permanent', joined:'12 Jun 2021', status:'Active', avatar:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop' },
    { id:'TCH-1031', name:'Vikram Nair', role:'Mathematics Teacher', department:'Academics', type:'Permanent', joined:'05 Jul 2022', status:'Active', avatar:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop' },
    { id:'STF-2108', name:'Meera Shah', role:'HR Coordinator', department:'Administration', type:'Permanent', joined:'18 Apr 2020', status:'Active', avatar:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop' },
    { id:'STF-2140', name:'Rohan Iyer', role:'Lab Assistant', department:'Science', type:'Contract', joined:'01 Apr 2025', status:'Probation', avatar:'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop' },
  ]);
  const [employeeForm, setEmployeeForm] = useState({ name:'', id:'', role:'', department:'Academics', type:'Permanent' });
  const rows = filterRows(payroll, q, ['name', 'role', 'status']);
  const exportCSV = () => downloadCSV('payslips.csv', ['Employee', 'Role', 'Gross', 'Deductions', 'Net', 'Status'], rows.map((p) => [p.name, p.role, p.gross, p.deductions, p.net, p.status]));
  const runPayroll = () => { setPayroll((x) => x.map((p) => ({ ...p, status: 'Paid' }))); setShowPayroll(false); setMessage(`${month} payroll has been processed successfully and payslips are ready.`); };
  const addEmployee = (event) => { event.preventDefault(); setEmployees((list) => [{ ...employeeForm, joined:new Date().toLocaleDateString('en-IN', {day:'2-digit',month:'short',year:'numeric'}), status:'Active', avatar:'' }, ...list]); setShowEmployee(false); setEmployeeForm({ name:'', id:'', role:'', department:'Academics', type:'Permanent' }); setMessage('Employee profile created and onboarding checklist assigned.'); };
  const nav = [
    ['overview','Overview',TrendingUp], ['people','People',Users], ['time','Attendance & Leave',CalendarDays], ['payroll','Payroll',ReceiptIndianRupee],
    ['benefits','Benefits & Claims',HeartHandshake], ['performance','Performance',Target], ['recruitment','Recruitment',BriefcaseBusiness], ['compliance','Compliance & Reports',ShieldCheck],
  ];
  const leave = [
    { name:'Ananya Rao', type:'Casual Leave', dates:'26–27 Aug', days:2, cover:'Vikram Nair', status:'Pending' },
    { name:'Rohan Iyer', type:'Sick Leave', dates:'24 Aug', days:1, cover:'Lab Team', status:'Approved' },
    { name:'Priya Menon', type:'Earned Leave', dates:'02–06 Sep', days:5, cover:'Meera Das', status:'Pending' },
  ];
  const jobs = [
    { role:'Primary Mathematics Teacher', openings:2, applicants:24, stage:'8 shortlisted', owner:'Academic Coordinator' },
    { role:'School Counsellor', openings:1, applicants:11, stage:'3 interviews', owner:'Principal' },
    { role:'Transport Supervisor', openings:1, applicants:7, stage:'Screening', owner:'Operations Head' },
  ];
  const filteredEmployees = filterRows(employees, q, ['name','id','role','department','status']);
  return (
    <Layout>
      <PageTitle title="HR & Payroll" subtitle="Manage the complete employee lifecycle—from hiring and attendance to payroll, development and compliance."
        actions={<><Btn variant="outline" icon={Download} onClick={() => downloadCSV('hr-workforce-report.csv', ['Employee','ID','Role','Department','Type','Status'], employees.map(e => [e.name,e.id,e.role,e.department,e.type,e.status]))}>HR Report</Btn><Btn icon={UserPlus} onClick={() => setShowEmployee(true)}>Add Employee</Btn></>} />
      {message && <div className="mb-5 rounded-xl bg-green-50 border border-green-100 px-4 py-3 text-[13px] text-green-700">{message}</div>}
      <div className="mb-6 overflow-x-auto rounded-2xl border border-slate-100 bg-white p-1.5 shadow-sm"><LiquidPills tone="brand" value={tab} onChange={(key) => { setTab(key); setQ(''); }} tabs={nav.map(([id, label, icon]) => ({ id, label, icon }))} /></div>

      {tab === 'overview' && <>
        <StatCards items={[{label:'Total Employees',value:'138',icon:Users},{label:'Present Today',value:'128',icon:UserCheck,tint:'bg-green-50 text-green-600'},{label:'Payroll · Aug',value:'₹82.4L',icon:Wallet,tint:'bg-blue-50 text-blue-600'},{label:'Open HR Actions',value:'14',icon:Clock,tint:'bg-amber-50 text-amber-600'}]} />
        <div className="grid grid-cols-1 gap-6 xl:grid-cols-3">
          <Card title="HR action centre" subtitle="Priorities that need attention today." className="xl:col-span-2" pad="p-0"><div className="divide-y divide-slate-100">{[
            ['6 leave requests awaiting approval','Review employee leave and substitute coverage.',CalendarDays,'Review','amber'],
            ['August payroll ready for validation','Attendance, additions and deductions have been imported.',BadgeDollarSign,'Validate','blue'],
            ['9 employee documents expiring','Contracts, police verification and certifications.',FileText,'View','red'],
            ['4 probation reviews due this week','Complete confirmation decisions with department heads.',ClipboardCheck,'Start','purple'],
          ].map(([title,note,Icon,action,color]) => <button key={title} onClick={() => setTab(title.includes('payroll')?'payroll':title.includes('leave')?'time':title.includes('probation')?'performance':'compliance')} className="flex w-full items-center gap-4 px-6 py-4 text-left hover:bg-slate-50"><span className={`flex h-10 w-10 items-center justify-center rounded-xl bg-${color}-50 text-${color}-600`}><Icon className="h-4 w-4" /></span><span className="min-w-0 flex-1"><b className="block text-[12px] text-slate-800">{title}</b><small className="mt-1 block text-[10px] text-slate-400">{note}</small></span><span className="flex items-center gap-1 text-[10px] font-semibold text-[#C4141B]">{action}<ChevronRight className="h-3 w-3" /></span></button>)}</div></Card>
          <Card title="Workforce snapshot" subtitle="Current employee composition."><div className="space-y-4">{[['Teaching staff',92,67],['Administration',18,13],['Support staff',16,12],['Transport & facilities',12,8]].map(([label,count,pct]) => <div key={label}><div className="mb-1.5 flex justify-between text-[10px]"><span className="text-slate-500">{label}</span><b>{count}</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-[#C4141B] to-[#ED6A70]" style={{width:`${pct}%`}} /></div></div>)}<div className="grid grid-cols-2 gap-3 border-t border-slate-100 pt-4"><div className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] text-slate-400">Women</p><b className="text-[18px]">61%</b></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] text-slate-400">Avg. tenure</p><b className="text-[18px]">4.8y</b></div></div></div></Card>
          <Card title="Today’s attendance" subtitle="Staff presence as of 10:00 AM" className="xl:col-span-2"><div className="grid grid-cols-2 gap-4 sm:grid-cols-4">{[['Present','128','green'],['On leave','6','blue'],['Late','3','amber'],['Absent','1','red']].map(([label,value,color]) => <div key={label} className={`rounded-2xl bg-${color}-50 p-4`}><p className={`text-[9px] font-semibold uppercase tracking-wider text-${color}-600`}>{label}</p><b className="mt-2 block text-[24px] text-slate-900">{value}</b></div>)}</div></Card>
          <Card title="Upcoming" subtitle="Important workforce events"><div className="space-y-3">{[['26 Aug','New teacher orientation'],['30 Aug','Payroll disbursement'],['02 Sep','POSH committee meeting'],['05 Sep','Teachers’ Day programme']].map(([date,event]) => <div key={event} className="flex gap-3"><span className="rounded-lg bg-red-50 px-2 py-1 text-[9px] font-bold text-[#C4141B]">{date}</span><p className="text-[11px] font-medium text-slate-700">{event}</p></div>)}</div></Card>
        </div>
      </>}

      {tab === 'people' && <Card pad="p-0" className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 px-6 py-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-[16px] font-bold">Employee directory</h3><p className="mt-1 text-[10px] text-slate-400">Profiles, contracts, roles, documents and employment status.</p></div><SearchBar placeholder="Search employee, ID or department…" className="w-full sm:w-72" value={q} onChange={(e)=>setQ(e.target.value)} /></div><div className="overflow-x-auto"><Table columns={[{label:'Employee'},{label:'Employee ID'},{label:'Department'},{label:'Employment'},{label:'Joined'},{label:'Status'},{label:''}]}>{filteredEmployees.map(e => <tr key={e.id} className="border-b border-slate-50 hover:bg-slate-50"><td className="px-6 py-4"><div className="flex items-center gap-3"><Avatar src={e.avatar} alt={e.name} size={9} /><div><b className="block text-[12px] text-slate-800">{e.name}</b><small className="text-[9px] text-slate-400">{e.role}</small></div></div></td><td className="py-4 text-[11px] font-semibold text-slate-600">{e.id}</td><td className="py-4 text-[11px] text-slate-500">{e.department}</td><td className="py-4"><Badge color={e.type==='Permanent'?'blue':'purple'}>{e.type}</Badge></td><td className="py-4 text-[10px] text-slate-500">{e.joined}</td><td className="py-4"><Badge color={e.status==='Active'?'green':'amber'}>{e.status}</Badge></td><td className="py-4 pr-6"><button className="text-[10px] font-semibold text-[#C4141B]">View profile</button></td></tr>)}</Table></div></Card>}

      {tab === 'time' && <div className="space-y-6"><div className="grid grid-cols-1 gap-4 md:grid-cols-4">{[['Present today','128',UserCheck,'green'],['On leave','6',CalendarDays,'blue'],['Pending requests','6',Clock,'amber'],['Attendance exceptions','4',AlertTriangle,'red']].map(([label,value,Icon,color]) => <Card key={label} pad="p-4"><Icon className={`h-5 w-5 text-${color}-600`} /><b className="mt-3 block text-[22px]">{value}</b><p className="text-[10px] text-slate-400">{label}</p></Card>)}</div><Card title="Leave approval queue" subtitle="Review balances, dates and classroom coverage before approval." pad="p-0"><div className="overflow-x-auto"><Table columns={[{label:'Employee'},{label:'Leave type'},{label:'Dates'},{label:'Days'},{label:'Coverage'},{label:'Status'},{label:'Action'}]}>{leave.map(row => <tr key={row.name} className="border-b border-slate-50"><td className="px-6 py-4 text-[12px] font-semibold">{row.name}</td><td className="py-4 text-[11px] text-slate-500">{row.type}</td><td className="py-4 text-[11px] text-slate-500">{row.dates}</td><td className="py-4 text-[11px] font-semibold">{row.days}</td><td className="py-4 text-[11px] text-slate-500">{row.cover}</td><td className="py-4"><Badge color={row.status==='Approved'?'green':'amber'}>{row.status}</Badge></td><td className="py-4 pr-6"><div className="flex gap-2"><button className="rounded-lg bg-green-50 px-3 py-1.5 text-[9px] font-semibold text-green-700">Approve</button><button className="rounded-lg bg-red-50 px-3 py-1.5 text-[9px] font-semibold text-red-700">Decline</button></div></td></tr>)}</Table></div></Card><div className="grid grid-cols-1 gap-6 lg:grid-cols-2"><Card title="Leave policy & balances" subtitle="Casual, sick, earned, maternity and compensatory leave."><div className="grid grid-cols-2 gap-3">{[['Casual leave','12 days'],['Sick leave','10 days'],['Earned leave','18 days'],['Comp-off','As earned']].map(([a,b]) => <div key={a} className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] text-slate-500">{a}</p><b className="mt-1 block text-[13px]">{b}</b></div>)}</div><Btn variant="outline" className="mt-4" icon={Settings2}>Configure leave policy</Btn></Card><Card title="Attendance tools" subtitle="Connect biometric punches with payroll."><div className="space-y-2">{['Shift and weekly-off setup','Late arrival and half-day rules','Regularisation requests','Overtime and compensatory-off rules'].map(x => <button key={x} className="flex w-full items-center justify-between rounded-xl border border-slate-100 px-4 py-3 text-[11px] font-medium text-slate-700 hover:bg-slate-50">{x}<ChevronRight className="h-3 w-3" /></button>)}</div></Card></div></div>}

      {tab === 'payroll' && <><div className="mb-5 grid grid-cols-1 gap-4 md:grid-cols-4">{[['Gross payroll','₹82.4L',Wallet,'blue'],['Deductions','₹9.8L',TrendingUp,'amber'],['Net payable','₹72.6L',Banknote,'green'],['Exceptions','6',AlertTriangle,'red']].map(([label,value,Icon,color]) => <Card key={label} pad="p-4"><Icon className={`h-5 w-5 text-${color}-600`} /><b className="mt-3 block text-[21px]">{value}</b><p className="text-[10px] text-slate-400">{label}</p></Card>)}</div><Card title={`Payroll · ${month}`} subtitle="Salary components, statutory deductions, adjustments and payment status." pad="p-0"><div className="flex flex-col gap-3 border-b border-slate-100 px-6 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-2"><select value={month} onChange={(e)=>setMonth(e.target.value)} className="h-10 rounded-lg border border-slate-200 px-3 text-[11px]"><option>August 2026</option><option>July 2026</option><option>June 2026</option></select><SearchBar placeholder="Search payroll…" className="w-56" value={q} onChange={(e)=>setQ(e.target.value)} /></div><div className="flex gap-2"><Btn variant="outline" icon={Download} onClick={exportCSV}>Payslips</Btn><Btn icon={BadgeDollarSign} onClick={()=>setShowPayroll(true)}>Run Payroll</Btn></div></div><div className="overflow-x-auto"><Table columns={[{label:'Employee'},{label:'Role'},{label:'Gross'},{label:'Deductions'},{label:'Net Pay'},{label:'Status'}]}>{rows.map((p,i)=><tr key={i} className="border-b border-slate-50"><td className="px-6 py-4"><div className="flex items-center gap-3"><Avatar src={p.avatar} alt={p.name} size={8}/><b className="text-[12px]">{p.name}</b></div></td><td className="py-4 text-[11px] text-slate-500">{p.role}</td><td className="py-4 text-[11px]">{p.gross}</td><td className="py-4 text-[11px] text-red-500">-{p.deductions}</td><td className="py-4 text-[11px] font-bold">{p.net}</td><td className="py-4 pr-6"><Badge color={p.status==='Paid'?'green':p.status==='Processing'?'blue':'amber'}>{p.status}</Badge></td></tr>)}</Table></div></Card><div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-3">{[['Salary structures','Basic, HRA, allowances, incentives and deductions.',IndianRupee],['Statutory setup','PF, ESI, professional tax, TDS and labour welfare.',ShieldCheck],['Loans & advances','Employee loans, salary advances and recovery schedules.',Wallet]].map(([title,note,Icon]) => <Card key={title}><Icon className="h-5 w-5 text-[#C4141B]"/><h4 className="mt-3 text-[13px] font-bold">{title}</h4><p className="mt-1 text-[10px] leading-5 text-slate-400">{note}</p><button className="mt-3 text-[10px] font-semibold text-[#C4141B]">Manage setup →</button></Card>)}</div></>}

      {tab === 'benefits' && <div className="grid grid-cols-1 gap-6 xl:grid-cols-3"><Card title="Claims awaiting approval" subtitle="Reimbursements submitted by employees." className="xl:col-span-2" pad="p-0"><div className="divide-y divide-slate-100">{[['Vikram Nair','Training workshop','₹6,500','24 Aug'],['Meera Shah','Local travel','₹2,840','23 Aug'],['Rohan Iyer','Lab supplies','₹4,275','22 Aug']].map(([name,type,amount,date]) => <div key={name} className="flex items-center gap-4 px-6 py-4"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-green-50 text-green-600"><ReceiptIndianRupee className="h-4 w-4"/></span><div className="flex-1"><b className="block text-[12px]">{name}</b><small className="text-[9px] text-slate-400">{type} · {date}</small></div><b className="text-[12px]">{amount}</b><button className="rounded-lg bg-green-50 px-3 py-1.5 text-[9px] font-semibold text-green-700">Approve</button></div>)}</div></Card><Card title="Benefits coverage" subtitle="Active employee programmes."><div className="space-y-3">{[['Group health insurance','132 enrolled'],['Accident insurance','138 enrolled'],['Gratuity','104 eligible'],['Staff tuition benefit','27 families']].map(([a,b]) => <div key={a} className="rounded-xl border border-slate-100 p-3"><b className="block text-[11px]">{a}</b><small className="text-[9px] text-slate-400">{b}</small></div>)}</div></Card><Card title="Employee financial services" className="xl:col-span-3"><div className="grid grid-cols-1 gap-4 md:grid-cols-4">{[['Reimbursements','12 open',ReceiptIndianRupee],['Salary advances','3 active',Wallet],['Employee loans','8 running',Banknote],['Tax declarations','84% complete',FileText]].map(([a,b,Icon]) => <button key={a} className="rounded-2xl border border-slate-100 p-4 text-left hover:border-red-100 hover:bg-red-50/30"><Icon className="h-5 w-5 text-[#C4141B]"/><b className="mt-3 block text-[12px]">{a}</b><small className="text-[9px] text-slate-400">{b}</small></button>)}</div></Card></div>}

      {tab === 'performance' && <div className="space-y-6"><div className="grid grid-cols-1 gap-4 md:grid-cols-4">{[['Reviews due','18',ClipboardCheck],['Goals on track','82%',Target],['Training hours','416h',GraduationCap],['Recognition awards','12',Award]].map(([a,b,Icon]) => <Card key={a} pad="p-4"><Icon className="h-5 w-5 text-[#C4141B]"/><b className="mt-3 block text-[22px]">{b}</b><p className="text-[10px] text-slate-400">{a}</p></Card>)}</div><Card title="Performance cycle · 2026–27" subtitle="Goal setting, observations, appraisal and development plans." pad="p-0"><div className="divide-y divide-slate-100">{[['Goal setting','126 / 138 complete',91],['Mid-year review','Opens 15 September',8],['Classroom observations','64 / 92 complete',70],['Development plans','38 active plans',42]].map(([title,note,pct]) => <div key={title} className="px-6 py-4"><div className="flex justify-between"><div><b className="text-[12px]">{title}</b><p className="text-[9px] text-slate-400">{note}</p></div><span className="text-[11px] font-bold text-[#C4141B]">{pct}%</span></div><div className="mt-3 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#C4141B]" style={{width:`${pct}%`}}/></div></div>)}</div></Card><div className="grid grid-cols-1 gap-6 lg:grid-cols-2"><Card title="Learning & development" subtitle="Courses, workshops and certifications."><Btn icon={Plus}>Create training programme</Btn><div className="mt-4 space-y-2">{['CBSE competency-based learning · 42 enrolled','Child safeguarding refresher · 118 enrolled','Digital classroom tools · 31 enrolled'].map(x=><div key={x} className="rounded-xl bg-slate-50 p-3 text-[10px] font-medium text-slate-600">{x}</div>)}</div></Card><Card title="Recognition" subtitle="Celebrate employee contributions."><div className="rounded-2xl bg-gradient-to-r from-amber-50 to-orange-50 p-5"><Award className="h-6 w-6 text-amber-500"/><b className="mt-3 block text-[14px]">Educator of the Month</b><p className="mt-1 text-[11px] text-slate-600">Ananya Rao · English Department</p><button className="mt-3 text-[10px] font-semibold text-amber-700">View all nominations →</button></div></Card></div></div>}

      {tab === 'recruitment' && <div className="space-y-6"><div className="flex justify-end"><Btn icon={Plus}>Create Job Opening</Btn></div><Card title="Active recruitment" subtitle="Open roles and candidate pipelines." pad="p-0"><div className="overflow-x-auto"><Table columns={[{label:'Position'},{label:'Openings'},{label:'Applicants'},{label:'Current stage'},{label:'Hiring owner'},{label:''}]}>{jobs.map(job=><tr key={job.role} className="border-b border-slate-50"><td className="px-6 py-4 text-[12px] font-semibold">{job.role}</td><td className="py-4 text-[11px]">{job.openings}</td><td className="py-4 text-[11px]">{job.applicants}</td><td className="py-4"><Badge color="blue">{job.stage}</Badge></td><td className="py-4 text-[10px] text-slate-500">{job.owner}</td><td className="py-4 pr-6"><button className="text-[10px] font-semibold text-[#C4141B]">Open pipeline</button></td></tr>)}</Table></div></Card><div className="grid grid-cols-1 gap-6 lg:grid-cols-3">{[['Applicant tracking','42 candidates','From application to offer'],['Interview calendar','7 this week','Panels and evaluation forms'],['Onboarding','4 new joiners','Documents, induction and access']].map(([a,b,c])=><Card key={a}><BriefcaseBusiness className="h-5 w-5 text-[#C4141B]"/><b className="mt-3 block text-[13px]">{a}</b><p className="mt-1 text-[20px] font-bold">{b}</p><small className="text-[9px] text-slate-400">{c}</small></Card>)}</div></div>}

      {tab === 'compliance' && <div className="space-y-6"><div className="grid grid-cols-1 gap-4 md:grid-cols-4">{[['Compliance health','94%',ShieldCheck,'green'],['Documents expiring','9',FileText,'amber'],['Policy acknowledgements','91%',ClipboardCheck,'blue'],['Open audit items','3',AlertTriangle,'red']].map(([a,b,Icon,color])=><Card key={a} pad="p-4"><Icon className={`h-5 w-5 text-${color}-600`}/><b className="mt-3 block text-[22px]">{b}</b><p className="text-[10px] text-slate-400">{a}</p></Card>)}</div><div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><Card title="Statutory & policy compliance" subtitle="Recurring school employer obligations."><div className="space-y-2">{[['PF & ESI filing · August','Due 15 Sep','green'],['TDS deposit · August','Due 07 Sep','amber'],['POSH annual records','Up to date','green'],['Police verification renewals','6 pending','red'],['Employment contract renewals','3 due this month','amber']].map(([a,b,color])=><div key={a} className="flex items-center justify-between rounded-xl border border-slate-100 p-3"><span className="text-[10px] font-medium text-slate-700">{a}</span><Badge color={color}>{b}</Badge></div>)}</div></Card><Card title="Employee document centre" subtitle="Secure lifecycle records and expiry tracking."><div className="grid grid-cols-2 gap-3">{[['Identity & address','276 files'],['Qualifications','214 files'],['Contracts','138 files'],['Background checks','132 files'],['Tax declarations','116 files'],['Medical records','84 files']].map(([a,b])=><button key={a} className="rounded-xl bg-slate-50 p-3 text-left"><FileText className="h-4 w-4 text-[#C4141B]"/><b className="mt-2 block text-[10px]">{a}</b><small className="text-[9px] text-slate-400">{b}</small></button>)}</div><Btn variant="outline" icon={Upload} className="mt-4">Upload Documents</Btn></Card></div><Card title="HR reports" subtitle="Download audit-ready workforce and payroll reports."><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Employee master','Profile and employment data'],['Attendance & leave','Daily and monthly registers'],['Payroll register','Earnings, deductions and bank advice'],['Statutory report','PF, ESI, PT and TDS summaries'],['Attrition report','Joiners, exits and retention'],['Diversity report','Workforce composition'],['Training report','Learning and certification'],['Audit trail','Approvals and record changes']].map(([a,b])=><button key={a} onClick={()=>setMessage(`${a} report downloaded.`)} className="flex items-start gap-3 rounded-xl border border-slate-100 p-4 text-left hover:border-red-100 hover:bg-red-50/30"><Download className="mt-0.5 h-4 w-4 shrink-0 text-[#C4141B]"/><span><b className="block text-[10px]">{a}</b><small className="mt-1 block text-[9px] leading-4 text-slate-400">{b}</small></span></button>)}</div></Card></div>}

      {showEmployee && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4 backdrop-blur-sm" onClick={()=>setShowEmployee(false)}><form onSubmit={addEmployee} onClick={e=>e.stopPropagation()} className="w-full max-w-xl rounded-3xl bg-white p-7 shadow-2xl"><div className="flex items-start justify-between"><div><h3 className="text-[18px] font-bold">Add employee</h3><p className="mt-1 text-[10px] text-slate-400">Create the profile and begin onboarding.</p></div><button type="button" onClick={()=>setShowEmployee(false)}><X className="h-5 w-5 text-slate-400"/></button></div><div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2">{[['Full name','name'],['Employee ID','id'],['Designation','role']].map(([label,key])=><label key={key} className="text-[10px] font-semibold text-slate-500">{label}<input required value={employeeForm[key]} onChange={e=>setEmployeeForm({...employeeForm,[key]:e.target.value})} className="mt-1.5 h-11 w-full rounded-xl border border-slate-200 px-3 text-[12px] outline-none focus:border-red-300"/></label>)}<label className="text-[10px] font-semibold text-slate-500">Department<select value={employeeForm.department} onChange={e=>setEmployeeForm({...employeeForm,department:e.target.value})} className="mt-1.5 h-11 w-full rounded-xl border border-slate-200 px-3 text-[12px]"><option>Academics</option><option>Administration</option><option>Science</option><option>Operations</option><option>Transport</option></select></label><label className="text-[10px] font-semibold text-slate-500">Employment type<select value={employeeForm.type} onChange={e=>setEmployeeForm({...employeeForm,type:e.target.value})} className="mt-1.5 h-11 w-full rounded-xl border border-slate-200 px-3 text-[12px]"><option>Permanent</option><option>Contract</option><option>Part-time</option><option>Probation</option></select></label></div><div className="mt-6 flex justify-end gap-3"><Btn type="button" variant="outline" onClick={()=>setShowEmployee(false)}>Cancel</Btn><Btn type="submit" icon={UserPlus}>Create Employee</Btn></div></form></div>}
      {showPayroll && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl bg-white p-7 text-center shadow-2xl"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-red-50 text-[#C4141B]"><BadgeDollarSign className="h-7 w-7"/></span><h3 className="mt-5 text-[18px] font-bold">Run {month} payroll?</h3><p className="mt-2 text-[11px] leading-5 text-slate-500">This will process salaries for 138 employees, lock approved attendance inputs and generate payslips.</p><div className="mt-5 rounded-xl bg-slate-50 p-4 text-left text-[10px]"><div className="flex justify-between"><span>Net disbursement</span><b>₹72.6L</b></div><div className="mt-2 flex justify-between"><span>Exceptions needing review</span><b className="text-amber-600">6 employees</b></div></div><div className="mt-6 flex justify-center gap-3"><Btn variant="outline" onClick={()=>setShowPayroll(false)}>Cancel</Btn><Btn icon={BadgeDollarSign} onClick={runPayroll}>Confirm & Run</Btn></div></div></div>}
    </Layout>
  );
};

export const BiometricManagement = () => {
  const [q, setQ] = useState('');
  const [records, setRecords] = useState(BIOMETRIC);
  const [syncedAt, setSyncedAt] = useState('');
  const rows = filterRows(records, q, ['name', 'id', 'device', 'status']);
  const exportCSV = () => downloadCSV('biometric.csv', ['Employee', 'ID', 'In', 'Out', 'Device', 'Status'], rows.map((b) => [b.name, b.id, b.in, b.out, b.device, b.status]));
  const sync = () => { setRecords((list) => list.map((x) => x.status === 'Absent' ? x : { ...x, device: 'Gate-01' })); setSyncedAt(new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })); };
  return (
    <Layout>
      <PageTitle title="Biometric Management" subtitle="Live fingerprint attendance from campus devices."
        actions={<><Btn variant="outline" icon={Download} onClick={exportCSV}>Export</Btn><Btn icon={Fingerprint} onClick={sync}>Sync Devices</Btn></>} />
      {syncedAt && <div className="mb-5 rounded-xl bg-blue-50 border border-blue-100 px-4 py-3 text-[13px] text-blue-700">All connected devices were synced at {syncedAt}.</div>}
      <StatCards items={[
        { label: 'Devices Online', value: '6 / 6', icon: Fingerprint, tint: 'bg-green-50 text-green-600' },
        { label: 'Present', value: '128', icon: CheckCircle2, tint: 'bg-blue-50 text-blue-600' },
        { label: 'Absent', value: '10', icon: XCircle, tint: 'bg-indigo-50 text-[#4F46E5]' },
        { label: 'Late Punches', value: '7', icon: Clock, tint: 'bg-amber-50 text-amber-600' },
      ]} />
      <Card title="Today’s Punch Log" action={<SearchBar placeholder="Search..." className="w-56" value={q} onChange={(e) => setQ(e.target.value)} />}>
        <Table columns={[{label:'Employee'},{label:'ID'},{label:'Punch In'},{label:'Punch Out'},{label:'Device'},{label:'Status'}]}>
          {rows.map((b, i) => (
            <tr key={i} className="border-b border-gray-50 last:border-0 hover:bg-[#fafafa]">
              <td className="py-3"><div className="flex items-center gap-3"><Avatar src={b.avatar} alt={b.name} size={8} /><span className="text-[13px] font-medium text-[#333]">{b.name}</span></div></td>
              <td className="py-3 text-[13px] text-[#666]">{b.id}</td>
              <td className="py-3 text-[13px] text-[#666]">{b.in}</td>
              <td className="py-3 text-[13px] text-[#666]">{b.out}</td>
              <td className="py-3 text-[13px] text-[#666]">{b.device}</td>
              <td className="py-3"><Badge color={b.status==='Present'?'green':'red'}>{b.status}</Badge></td>
            </tr>
          ))}
          {rows.length === 0 && <tr><td colSpan={6} className="py-8 text-center text-[13px] text-[#999]">No records found.</td></tr>}
        </Table>
      </Card>
    </Layout>
  );
};
