import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, CheckCircle2, FileText, Loader2, MapPin, Printer, RefreshCw, Send, TicketCheck, Users } from 'lucide-react';
import Layout from '../../../layouts/Layout';
import { Badge, Btn, Card, PageTitle, StatCards, Table } from '../../../components/Shared';
import { printPage } from '../../../utils';
import api from '../../../api/client';

const control='h-12 w-full rounded-xl border border-slate-200 bg-white px-3.5 text-[12px] font-semibold text-slate-700 outline-none focus:border-indigo-300 focus:ring-4 focus:ring-indigo-50 disabled:opacity-50';

function CreateHallTickets(){
 const [tickets,setTickets]=useState([]),[exams,setExams]=useState([]),[students,setStudents]=useState([]),[results,setResults]=useState(null);
 const [className,setClassName]=useState(''),[section,setSection]=useState(''),[examId,setExamId]=useState(''),[venue,setVenue]=useState('');
 const [instructions,setInstructions]=useState('Bring the school ID card and required stationery. Report 30 minutes before the examination.');
 const [feeRule,setFeeRule]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{setLoading(true);try{const [t,e,s]=await Promise.all([api.get('/parent-center/hall-tickets'),api.get('/exams'),api.get('/students')]);setTickets(t.data||[]);setExams(e.data||[]);setStudents(s.data||[]);}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const schoolExams=useMemo(()=>exams.filter(e=>e.status!=='Draft'),[exams]);
 const classes=[...new Set(schoolExams.map(e=>e.class_name).filter(Boolean))].sort();
 const sections=[...new Set(schoolExams.filter(e=>e.class_name===className).map(e=>e.section).filter(Boolean))].sort();
 const examOptions=schoolExams.filter(e=>e.class_name===className&&e.section===section), exam=examOptions.find(e=>e.id===examId);
 const eligible=students.filter(s=>s.class_name===className&&s.section===section&&s.status!=='Inactive');
 const subjects=exam?[...new Set((exam.subjects?.length?exam.subjects:[exam.subject]).filter(s=>s&&s!=='All Subjects'))]:[];
 const papers=subjects.map(subject=>({subject,date:exam?.date||'',time:exam?.start_time&&exam?.end_time?`${exam.start_time} – ${exam.end_time}`:exam?.start_time||'Time pending',max_marks:exam?.max_marks||100}));
 const existing=tickets.find(t=>t.exam_id===examId);
 const chooseExam=async id=>{setExamId(id);setResults(null);setMessage('');const selected=examOptions.find(e=>e.id===id);setVenue(selected?.room||'');if(selected)try{setResults((await api.get('/results',{params:{class_name:selected.class_name,section:selected.section,exam_title:selected.title}})).data);}catch{setResults(null);}};
 const save=async status=>{if(!exam||!venue.trim()||!papers.length){setMessage('Select a school exam with subjects and confirm the venue.');return;}setSaving(true);try{const payload={exam_id:exam.id,title:exam.title,class_name:exam.class_name,section:exam.section,venue:venue.trim(),instructions:instructions.trim(),papers,status,block_on_fee_due:feeRule};existing?await api.put(`/parent-center/hall-tickets/${existing.id}`,payload):await api.post('/parent-center/hall-tickets',payload);setMessage(status==='Published'?`Hall ticket published for ${eligible.length} eligible students.`:'Hall ticket draft saved.');await load();}catch(error){setMessage(error.response?.data?.detail||'Could not save the hall ticket.');}finally{setSaving(false);}};
 return <Layout>
  <PageTitle title="Hall Tickets" subtitle="Create accurate hall tickets from Exams, Student List and Marks Management." actions={<Btn variant="outline" icon={RefreshCw} onClick={load}>Refresh</Btn>}/>
  <StatCards items={[{ label: 'Published', value: tickets.filter((ticket) => ticket.status === 'Published').length, icon: TicketCheck, tint: 'bg-emerald-50 text-emerald-700' }, { label: 'School exams', value: schoolExams.length, icon: FileText }, { label: 'Eligible', value: exam ? eligible.length : '—', icon: Users }]} />
  {message&&<div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-[12px] text-amber-800">{message}</div>}
  <div className="grid gap-6 xl:grid-cols-[390px_1fr]"><Card title="Prepare hall ticket" subtitle="Select only an exam already created by the school."><div className="space-y-3"><select className={control} value={className} onChange={e=>{setClassName(e.target.value);setSection('');setExamId('');}}><option value="">Select Class</option>{classes.map(x=><option key={x}>{x}</option>)}</select><select className={control} value={section} disabled={!className} onChange={e=>{setSection(e.target.value);setExamId('');}}><option value="">Select Section</option>{sections.map(x=><option key={x}>{x}</option>)}</select><select className={control} value={examId} disabled={!section} onChange={e=>chooseExam(e.target.value)}><option value="">Select Exam</option>{examOptions.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select><input className={control} value={venue} onChange={e=>setVenue(e.target.value)} placeholder="Examination venue"/><textarea className={`${control} h-24 py-3`} value={instructions} onChange={e=>setInstructions(e.target.value)}/><label className="flex gap-2 rounded-xl bg-slate-50 p-3 text-[11px]"><input type="checkbox" checked={feeRule} onChange={e=>setFeeRule(e.target.checked)}/> Apply fee-eligibility rule</label><div className="grid grid-cols-2 gap-2"><Btn variant="outline" icon={FileText} disabled={saving||!exam} onClick={()=>save('Draft')}>Save Draft</Btn><Btn icon={saving?Loader2:Send} disabled={saving||!exam} onClick={()=>save('Published')}>Publish</Btn></div></div></Card>
  <div className="space-y-6"><Card title="Exam-linked ticket preview" subtitle={exam?`${exam.title} · ${className} · ${section}`:'Select an exam to preview its official schedule.'} action={exam?<Btn variant="outline" icon={Printer} onClick={printPage}>Print / Download</Btn>:null}>{!exam?<div className="py-14 text-center text-[12px] text-slate-400"><TicketCheck className="mx-auto mb-3 h-9 w-9 text-indigo-200"/>Choose Class, Section and Exam</div>:<div id="hall-ticket-print" className="overflow-hidden rounded-2xl border-2 border-indigo-900"><div className="bg-indigo-950 p-5 text-white"><p className="text-[9px] uppercase tracking-wider text-indigo-200">Official examination hall ticket</p><h3 className="mt-2 text-[21px] font-bold">{exam.title}</h3><p className="text-[10px] text-indigo-100/70">{className} · {section} · {eligible.length} eligible students</p></div><div className="grid grid-cols-3 gap-3 bg-slate-50 p-4">{[[CalendarDays,'Date',exam.date||'Pending'],[MapPin,'Venue',venue||'Pending'],[CheckCircle2,'Marks status',results?.rows?.length?`${results.rows.length} results recorded`:'Not entered']].map(([Icon,label,value])=><div key={label} className="rounded-xl bg-white p-3"><Icon className="mb-2 h-4 w-4 text-indigo-600"/><p className="text-[8px] uppercase text-slate-400">{label}</p><p className="mt-1 text-[11px] font-bold">{value}</p></div>)}</div><div className="space-y-2 p-5">{papers.map((p,i)=><div key={p.subject} className="grid grid-cols-[32px_1fr_110px] items-center gap-3 rounded-xl border p-3"><b className="text-indigo-600">{i+1}</b><div><p className="text-[12px] font-bold">{p.subject}</p><p className="text-[9px] text-slate-400">Maximum marks: {p.max_marks}</p></div><p className="text-[10px] text-slate-500">{p.date}<br/>{p.time}</p></div>)}</div></div>}</Card>
  <Card title="Hall ticket register" subtitle="One record per school-created exam." pad="p-0"><Table columns={[{label:'Exam'},{label:'Class / Section'},{label:'Papers'},{label:'Status'}]}>{tickets.map(t=><tr key={t.id} className="border-b"><td className="px-6 py-3 text-[12px] font-bold">{t.title}</td><td className="py-3 text-[11px]">{t.class_name} · {t.section}</td><td className="py-3 text-[11px]">{t.papers?.length||0}</td><td className="py-3"><Badge color={t.status==='Published'?'green':'amber'}>{t.status}</Badge></td></tr>)}</Table>{!loading&&!tickets.length&&<p className="py-12 text-center text-[12px] text-slate-400">No hall tickets created yet.</p>}</Card></div></div>
 </Layout>;
}

function ViewHallTickets(){
 const [tickets,setTickets]=useState([]),[students,setStudents]=useState([]),[loading,setLoading]=useState(true),[ticketId,setTicketId]=useState(''),[studentId,setStudentId]=useState('');
 useEffect(()=>{Promise.all([api.get('/parent-center/hall-tickets'),api.get('/students')]).then(([t,s])=>{setTickets((t.data||[]).filter(x=>x.status==='Published'));setStudents(s.data||[]);}).finally(()=>setLoading(false));},[]);
 const ticket=tickets.find(x=>x.id===ticketId);
 const eligible=students.filter(s=>ticket&&s.class_name===ticket.class_name&&s.section===ticket.section&&s.status!=='Inactive');
 const selectedStudents=studentId==='__all__'?eligible:eligible.filter(s=>s.id===studentId);
 const settings=(()=>{try{return JSON.parse(localStorage.getItem('orison-system-settings')||'{}');}catch{return {};}})();
 const schoolName=settings.schoolName||'Orison Main Campus', address=settings.address||'School address not configured', contact=[settings.phone,settings.email,settings.website].filter(Boolean).join(' · ');
 return <Layout><PageTitle title="View Hall Tickets" subtitle="Print one student on one A4 page, or select all students to print two hall tickets per A4 page." actions={<Btn variant="outline" icon={RefreshCw} onClick={()=>window.location.reload()}>Refresh</Btn>}/>
  <Card title="Select student hall ticket" subtitle="Choose one student or all eligible students after selecting a published exam."><div className="grid gap-3 md:grid-cols-2"><select className={control} value={ticketId} disabled={loading} onChange={e=>{setTicketId(e.target.value);setStudentId('');}}><option value="">Select published exam</option>{tickets.map(t=><option key={t.id} value={t.id}>{t.title} · {t.class_name} · {t.section}</option>)}</select><select className={control} value={studentId} disabled={!ticket} onChange={e=>setStudentId(e.target.value)}><option value="">Select student</option>{eligible.length>0&&<option value="__all__">All Students ({eligible.length})</option>}{eligible.map(s=><option key={s.id} value={s.id}>{s.name} · {s.roll||s.admission_no||s.id}</option>)}</select></div></Card>
  {!selectedStudents.length?<div className="mt-6 rounded-3xl border border-dashed border-indigo-200 bg-white py-16 text-center"><TicketCheck className="mx-auto h-10 w-10 text-indigo-200"/><p className="mt-3 text-[13px] font-semibold text-slate-600">Select an exam and student, or choose All Students.</p></div>:<><div className="my-5 flex justify-end gap-2"><Btn variant="outline" icon={Printer} onClick={printPage}>Print</Btn><Btn icon={FileText} onClick={printPage}>{studentId==='__all__'?`Download All (${selectedStudents.length})`:'Download Student PDF'}</Btn></div><div id="hall-ticket-batch" className="space-y-5">{selectedStudents.map(student=><div key={student.id} className={`student-hall-ticket mx-auto max-w-[900px] bg-white p-7 text-slate-900 shadow-xl ring-1 ring-slate-200 ${studentId==='__all__'?'bulk-ticket':'single-ticket'}`}>
   <style>{`@media print{body *{visibility:hidden!important}#hall-ticket-batch,#hall-ticket-batch *{visibility:visible!important}#hall-ticket-batch{position:absolute;left:0;top:0;width:100%;margin:0!important}.student-hall-ticket{box-shadow:none!important;max-width:none!important;break-inside:avoid;box-sizing:border-box}.single-ticket{height:277mm;page-break-after:always}.bulk-ticket{height:138.5mm;padding:4mm!important;margin:0!important;overflow:hidden}.bulk-ticket:nth-child(2n){page-break-after:always}.bulk-ticket header{grid-template-columns:52px 1fr 52px!important;padding-bottom:5px!important}.bulk-ticket header>div:first-child{width:46px!important;height:46px!important;font-size:18px!important}.bulk-ticket header h1{font-size:15px!important}.bulk-ticket header p{font-size:7px!important}.bulk-ticket section{margin-top:5px!important}.bulk-ticket table{font-size:7px!important}.bulk-ticket th,.bulk-ticket td{padding:3px!important}.bulk-ticket td:last-child{height:24px!important;min-width:80px!important}.bulk-ticket footer{margin-top:14px!important;font-size:7px!important}@page{size:A4 portrait;margin:10mm}}`}</style>
   <header className="grid grid-cols-[86px_1fr_86px] items-center border-b-4 border-indigo-950 pb-5 text-center"><div className="flex h-20 w-20 items-center justify-center rounded-full border-4 border-indigo-950 bg-indigo-50 font-poppins text-[30px] font-black text-indigo-950">{schoolName.slice(0,1)}</div><div><h1 className="font-poppins text-[27px] font-black uppercase tracking-wide text-indigo-950">{schoolName}</h1><p className="mt-1 text-[11px] font-semibold text-slate-600">{address}</p>{contact&&<p className="mt-1 text-[9px] text-slate-500">{contact}</p>}<div className="mt-3 inline-block rounded-full bg-indigo-950 px-5 py-1.5 text-[11px] font-bold uppercase tracking-[.16em] text-white">Examination Hall Ticket</div></div><div className="rounded-xl border border-slate-300 p-2 text-[9px] font-bold text-slate-500">STUDENT<br/>PHOTO<div className="mt-2 h-12 rounded bg-slate-50"/></div></header>
   <section className="mt-5 grid grid-cols-4 gap-px overflow-hidden rounded-xl border border-slate-300 bg-slate-300 text-[11px]">{[['Student Name',student.name],['Admission No.',student.admission_no||student.id],['Roll No.',student.roll||'—'],['Class / Section',`${student.class_name} / ${student.section}`],['Exam',ticket.title],['Venue',ticket.venue],['Date of Birth',student.dob||'—'],['Academic Year',settings.academicYear||'—']].map(([label,value])=><div key={label} className="bg-white p-3"><b className="block text-[8px] uppercase tracking-wider text-slate-400">{label}</b><span className="mt-1 block font-bold text-slate-800">{value}</span></div>)}</section>
   <section className="mt-6"><h2 className="mb-2 text-[11px] font-black uppercase tracking-wider text-indigo-950">Examination Schedule</h2><table className="w-full border-collapse text-[11px]"><thead><tr className="bg-indigo-950 text-white"><th className="border p-3 text-left">No.</th><th className="border p-3 text-left">Subject</th><th className="border p-3">Date</th><th className="border p-3">Time</th><th className="border p-3">Max Marks</th><th className="border p-3">Invigilator Signature</th></tr></thead><tbody>{(ticket.papers||[]).map((p,i)=><tr key={`${p.subject}-${i}`}><td className="border border-slate-300 p-3">{i+1}</td><td className="border border-slate-300 p-3 font-bold">{p.subject}</td><td className="border border-slate-300 p-3 text-center">{p.date||'—'}</td><td className="border border-slate-300 p-3 text-center">{p.time||'—'}</td><td className="border border-slate-300 p-3 text-center">{p.max_marks||'—'}</td><td className="h-16 min-w-[130px] border border-slate-300 bg-white"></td></tr>)}</tbody></table></section>
   {ticket.instructions&&<section className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-[10px] leading-5"><b>Instructions:</b> {ticket.instructions}</section>}<footer className="mt-14 grid grid-cols-3 gap-14 text-center text-[10px] font-bold"><div className="border-t border-slate-500 pt-2">Class Teacher</div><div className="border-t border-slate-500 pt-2">Examination In-charge</div><div className="border-t border-slate-500 pt-2">Principal</div></footer>
  </div>)}</div></>}
 </Layout>;
}

export default function HallTicketsManagement({mode='create'}){return mode==='view'?<ViewHallTickets/>:<CreateHallTickets/>;}
