import React, { useEffect, useState } from 'react';
import Layout from '../../components/Layout';
import { PageTitle, Card, Btn, Badge, Table } from '../../components/Shared';
import { ArrowRightLeft, GraduationCap, Check, Loader2 } from 'lucide-react';
import api from '../../api';

const Person = ({ student }) => <div className="flex items-center gap-3"><img src={student.avatar} alt="" className="w-8 h-8 rounded-full object-cover"/><span className="text-[13px] font-medium text-[#1a1a1a]">{student.name}</span></div>;

export const PromoteStudent = () => {
  const [students, setStudents] = useState([]); const [selected, setSelected] = useState([]); const [setup, setSetup] = useState({ academic_year: '', classes: [] }); const [target, setTarget] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([api.get('/students'), api.get('/academic-structure')]).then(([studentData, structureData]) => { setStudents(studentData.data); setSetup(structureData.data); }).finally(() => setLoading(false)); }, []);
  const toggle = (id) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  return <Layout><PageTitle title="Promote Student" subtitle="This list uses only real students from your school database." />
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-6"><select value={target} onChange={(e) => setTarget(e.target.value)} className="h-11 rounded-lg border border-gray-200 px-3 text-[13px]"><option value="">Select next class</option>{setup.classes.map((item) => <option key={item.id} value={item.name}>{item.name}</option>)}</select><div className="h-11 rounded-lg bg-gray-50 px-3 flex items-center text-[13px] text-[#666]">Academic year: {setup.academic_year || 'Not configured'}</div><Btn icon={GraduationCap} className="w-full" onClick={() => alert(target && selected.length ? 'Promotion selection is ready for review.' : 'Select students and the next class first.')}>Promote Selected ({selected.length})</Btn></div>
    <Card title="Current Students" subtitle="No sample students are shown.">{loading ? <div className="py-10 text-center"><Loader2 className="inline w-5 h-5 animate-spin text-[#888]"/></div> : <Table columns={[{label:''},{label:'Student'},{label:'Current Class'},{label:'Section'},{label:'Select',align:'center'}]}>{students.map((student, index) => <tr key={student.id} className="border-b border-gray-50 last:border-0"><td className="py-3 text-[12px] text-[#aaa]">{index + 1}</td><td className="py-3"><Person student={student}/></td><td className="py-3 text-[13px] text-[#666]">{student.class_name}</td><td className="py-3 text-[13px] text-[#666]">{student.section}</td><td className="py-3 text-center"><button onClick={() => toggle(student.id)} className={`w-5 h-5 rounded flex items-center justify-center mx-auto ${selected.includes(student.id) ? 'bg-[#C4141B]' : 'border border-gray-300'}`}>{selected.includes(student.id) && <Check className="w-3.5 h-3.5 text-white"/>}</button></td></tr>)}{!students.length && <tr><td colSpan="5" className="py-10 text-center text-[13px] text-[#999]">No students have been added yet.</td></tr>}</Table>}</Card>
  </Layout>;
};

export const TransferStudent = () => {
  const [students, setStudents] = useState([]); const [selected, setSelected] = useState(''); const [loading, setLoading] = useState(true); const student = students.find((item) => item.id === selected);
  useEffect(() => { api.get('/students').then(({ data }) => setStudents(data)).finally(() => setLoading(false)); }, []);
  return <Layout><PageTitle title="Transfer Student" subtitle="Select a real enrolled student to issue a transfer." />
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><Card title="Transfer Details" className="lg:col-span-1 self-start"><div className="space-y-4"><select value={selected} onChange={(e) => setSelected(e.target.value)} className="w-full h-11 rounded-lg border border-gray-200 px-3 text-[13px]"><option value="">Select student</option>{students.map((item) => <option key={item.id} value={item.id}>{item.name} — {item.class_name} {item.section}</option>)}</select><select className="w-full h-11 rounded-lg border border-gray-200 px-3 text-[13px]"><option>Branch Transfer</option><option>School Withdrawal</option><option>Section Change</option></select><input placeholder="Reason for transfer" className="w-full h-11 rounded-lg border border-gray-200 px-3 text-[13px]"/><input type="date" className="w-full h-11 rounded-lg border border-gray-200 px-3 text-[13px]"/><Btn icon={ArrowRightLeft} className="w-full" onClick={() => alert(student ? `Transfer request prepared for ${student.name}.` : 'Select a student first.')}>Issue Transfer</Btn></div></Card><Card title="Selected Student" className="lg:col-span-2 self-start">{loading ? <div className="py-10 text-center"><Loader2 className="inline w-5 h-5 animate-spin text-[#888]"/></div> : student ? <div className="flex items-center gap-4 p-3"><Person student={student}/><Badge color="blue">{student.class_name} · {student.section}</Badge></div> : <p className="py-10 text-center text-[13px] text-[#999]">Select a real student from the list. No demo transfers are displayed.</p>}</Card></div>
  </Layout>;
};
