import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import Layout from '../../components/Layout';
import { Badge, Btn, Card, PageTitle, SearchBar, StatCards, Table } from '../../components/Shared';
import { CheckCircle2, Download, Edit3, Eye, Plus, Save, Trash2, Upload, Users } from 'lucide-react';
import api from '../../api';

const emptyTeacher = { name: '', employee_id: '', phone: '', email: '', primary_subject: '', qualification: '', status: 'Active' };
const input = 'mt-1 h-10 w-full rounded-lg border border-gray-200 bg-white px-3 text-[13px] focus:outline-none focus:ring-2 focus:ring-red-100';
const downloadBlob = (data, filename) => { const url = window.URL.createObjectURL(new Blob([data])); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); window.URL.revokeObjectURL(url); };

export const AddTeacher = () => {
  const [form, setForm] = useState(emptyTeacher); const [notice, setNotice] = useState(''); const [saving, setSaving] = useState(false); const [bulkResult, setBulkResult] = useState(null); const fileRef = useRef(null);
  const set = (key) => (event) => setForm({ ...form, [key]: event.target.value });
  const save = async () => { setSaving(true); setNotice(''); try { const { data } = await api.post('/teachers', form); setNotice(`${data.name} was added successfully.`); setForm(emptyTeacher); } catch (error) { setNotice(error.response?.data?.detail || 'Could not add teacher.'); } finally { setSaving(false); } };
  const downloadTemplate = async () => { const response = await api.get('/teachers-template', { responseType: 'blob' }); downloadBlob(response.data, 'teachers-template.csv'); };
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; setBulkResult(null); const data = new FormData(); data.append('file', file); try { const response = await api.post('/teachers/bulk', data, { headers: { 'Content-Type': 'multipart/form-data' } }); setBulkResult(response.data); } catch (error) { setBulkResult({ inserted: 0, errors: [{ row: 0, error: error.response?.data?.detail || 'Upload failed' }] }); } event.target.value = ''; };
  return <Layout><PageTitle title="Add Teacher" subtitle="Add one teacher now or import your complete teacher directory using a CSV file." />
    {notice && <div className={`mb-5 rounded-xl border px-4 py-3 text-[13px] ${notice.includes('successfully') ? 'border-green-100 bg-green-50 text-green-700' : 'border-red-100 bg-red-50 text-red-700'}`}>{notice}</div>}
    <div className="grid grid-cols-1 gap-5 xl:grid-cols-3"><Card title="Add single teacher" subtitle="Employee ID is optional; the system creates one if left blank." className="xl:col-span-2"><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><label className="text-[12px] font-medium text-[#555]">Teacher name *<input value={form.name} onChange={set('name')} placeholder="Full name" className={input} /></label><label className="text-[12px] font-medium text-[#555]">Employee ID<input value={form.employee_id} onChange={set('employee_id')} placeholder="e.g. TCH-1001" className={input} /></label><label className="text-[12px] font-medium text-[#555]">Phone number<input value={form.phone} onChange={set('phone')} placeholder="Phone number" className={input} /></label><label className="text-[12px] font-medium text-[#555]">Email<input value={form.email} onChange={set('email')} placeholder="teacher@school.com" className={input} /></label><label className="text-[12px] font-medium text-[#555]">Primary subject<input value={form.primary_subject} onChange={set('primary_subject')} placeholder="e.g. Mathematics" className={input} /></label><label className="text-[12px] font-medium text-[#555]">Qualification<input value={form.qualification} onChange={set('qualification')} placeholder="e.g. B.Ed, M.Sc" className={input} /></label><label className="text-[12px] font-medium text-[#555]">Status<select value={form.status} onChange={set('status')} className={input}><option>Active</option><option>On Leave</option><option>Inactive</option></select></label></div><div className="mt-6 flex justify-end"><Btn icon={Save} onClick={save} disabled={saving}>{saving ? 'Saving…' : 'Add Teacher'}</Btn></div></Card>
      <Card title="Bulk import teachers" subtitle="Use our template to avoid column errors."><input ref={fileRef} type="file" accept=".csv" className="hidden" onChange={upload} /><div className="space-y-3"><Btn variant="outline" icon={Download} onClick={downloadTemplate} className="w-full">Download CSV template</Btn><Btn icon={Upload} onClick={() => fileRef.current?.click()} className="w-full">Upload completed CSV</Btn></div>{bulkResult && <div className={`mt-5 rounded-xl p-3 text-[12px] ${bulkResult.inserted ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'}`}><p className="font-semibold">{bulkResult.inserted} teacher(s) imported.</p>{bulkResult.errors?.length > 0 && <p className="mt-1">{bulkResult.errors.length} row(s) need correction: {bulkResult.errors.slice(0, 2).map((item) => `row ${item.row} (${item.error})`).join(', ')}</p>}</div>}</Card></div>
  </Layout>;
};

export const ViewTeachers = () => {
  const [teachers, setTeachers] = useState([]); const [q, setQ] = useState(''); const [editing, setEditing] = useState(null); const [notice, setNotice] = useState('');
  const load = useCallback(() => api.get('/teachers').then(({ data }) => setTeachers(data)).catch(() => setTeachers([])), []); useEffect(() => { load(); }, [load]);
  const rows = useMemo(() => teachers.filter((teacher) => [teacher.name, teacher.id, teacher.subject, teacher.phone, teacher.email].join(' ').toLowerCase().includes(q.toLowerCase())), [teachers, q]);
  const saveEdit = async () => { try { await api.put(`/teachers/${editing.id}`, editing); setEditing(null); setNotice('Teacher details updated.'); load(); } catch (error) { setNotice(error.response?.data?.detail || 'Could not update teacher.'); } };
  const active = teachers.filter((teacher) => teacher.status === 'Active').length;
  return <Layout><PageTitle title="View Teachers" subtitle="View the live teacher directory and edit teacher details." actions={<Btn variant="outline" icon={Download} onClick={() => downloadBlob([['Employee ID', 'Teacher Name', 'Subject', 'Phone', 'Email', 'Status'], ...rows.map((teacher) => [teacher.id, teacher.name, teacher.subject, teacher.phone, teacher.email, teacher.status])].map((row) => row.join(',')).join('\n'), 'teachers.csv')}>Export CSV</Btn>} />
    {notice && <div className="mb-5 rounded-xl border border-green-100 bg-green-50 px-4 py-3 text-[13px] text-green-700">{notice}</div>}<StatCards items={[{ label: 'Total Teachers', value: teachers.length, icon: Users }, { label: 'Active Teachers', value: active, icon: CheckCircle2, tint: 'bg-green-50 text-green-600' }, { label: 'Unallocated Teachers', value: teachers.filter((teacher) => !teacher.subject).length, icon: Users, tint: 'bg-amber-50 text-amber-600' }]} />
    <Card title="Teacher directory" action={<SearchBar value={q} onChange={(event) => setQ(event.target.value)} placeholder="Search teachers..." className="w-64" />} pad="p-0"><div className="overflow-x-auto"><Table columns={[{ label: 'Teacher' }, { label: 'Employee ID' }, { label: 'Primary subject' }, { label: 'Phone / Email' }, { label: 'Status' }, { label: 'Action' }]}>{rows.map((teacher) => <tr key={teacher.id} className="border-b border-gray-50"><td className="px-6 py-3 text-[13px] font-semibold">{teacher.name}<span className="mt-0.5 block text-[11px] font-normal text-[#999]">{teacher.qualification || 'Qualification not added'}</span></td><td className="py-3 text-[13px] text-[#666]">{teacher.id}</td><td className="py-3 text-[13px] text-[#666]">{teacher.subject || '—'}</td><td className="py-3 text-[12px] text-[#666]">{teacher.phone || '—'}<span className="mt-0.5 block">{teacher.email || ''}</span></td><td className="py-3"><Badge color={teacher.status === 'Active' ? 'green' : teacher.status === 'On Leave' ? 'amber' : 'gray'}>{teacher.status || 'Active'}</Badge></td><td className="py-3 pr-6"><button onClick={() => setEditing({ ...teacher, primary_subject: teacher.subject || '' })} className="inline-flex items-center gap-1 text-[12px] font-semibold text-[#C4141B]"><Edit3 size={14} /> View / Edit</button></td></tr>)}</Table>{!rows.length && <div className="py-10 text-center text-[13px] text-[#999]">No teachers found.</div>}</div></Card>
    {editing && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-xl"><div className="mb-5 flex items-center justify-between"><h2 className="font-poppins text-[20px] font-bold">View / Edit Teacher</h2><button onClick={() => setEditing(null)} className="text-[13px] text-[#777]">Close</button></div><div className="grid grid-cols-1 gap-4 md:grid-cols-2">{[['name', 'Teacher name'], ['phone', 'Phone'], ['email', 'Email'], ['primary_subject', 'Primary subject'], ['qualification', 'Qualification']].map(([key, label]) => <label key={key} className="text-[12px] font-medium text-[#555]">{label}<input value={editing[key] || ''} onChange={(event) => setEditing({ ...editing, [key]: event.target.value })} className={input} /></label>)}<label className="text-[12px] font-medium text-[#555]">Status<select value={editing.status || 'Active'} onChange={(event) => setEditing({ ...editing, status: event.target.value })} className={input}><option>Active</option><option>On Leave</option><option>Inactive</option></select></label></div><div className="mt-6 flex justify-end gap-3"><Btn variant="outline" onClick={() => setEditing(null)}>Cancel</Btn><Btn icon={Save} onClick={saveEdit}>Save Changes</Btn></div></div></div>}
  </Layout>;
};

const useSchoolStructure = () => { const [structure, setStructure] = useState({ academic_year: '', classes: [] }); useEffect(() => { api.get('/academic-structure').then(({ data }) => setStructure(data || { academic_year: '', classes: [] })).catch(() => setStructure({ academic_year: '', classes: [] })); }, []); return structure; };

export const AssignTeachers = () => {
  const structure = useSchoolStructure(); const [teachers, setTeachers] = useState([]); const [form, setForm] = useState({ class_name: '', section: '', subject: '', teacher_id: '' }); const [notice, setNotice] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { api.get('/teachers').then(({ data }) => setTeachers(data.filter((teacher) => teacher.status !== 'Inactive'))).catch(() => setTeachers([])); }, []);
  const selectedClass = structure.classes?.find((item) => item.name === form.class_name); const selectedSection = selectedClass?.sections?.find((item) => item.name === form.section); const subjects = selectedSection?.subjects || [];
  const save = async () => { const teacher = teachers.find((item) => item.id === form.teacher_id); if (!teacher || !form.subject || !form.section) { setNotice('Choose Class, Section, Subject and Teacher.'); return; } setSaving(true); try { await api.post('/teacher-allocations', { ...form, teacher_name: teacher.name, academic_year: structure.academic_year }); setNotice(`${teacher.name} was assigned to ${form.subject}.`); setForm({ class_name: '', section: '', subject: '', teacher_id: '' }); } catch (error) { setNotice(error.response?.data?.detail || 'Could not save allocation.'); } finally { setSaving(false); } };
  return <Layout><PageTitle title="Assign Teacher" subtitle="Assign one teacher to a specific Class, Section and Subject from your Academic Setup." />{notice && <div className={`mb-5 rounded-xl border px-4 py-3 text-[13px] ${notice.includes('was assigned') ? 'border-green-100 bg-green-50 text-green-700' : 'border-amber-100 bg-amber-50 text-amber-700'}`}>{notice}</div>}<Card title="Teacher allocation"><div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="text-[12px] font-medium text-[#555]">Class<select value={form.class_name} onChange={(event) => setForm({ ...form, class_name: event.target.value, section: '', subject: '' })} className={input}><option value="">Select class</option>{(structure.classes || []).map((item) => <option key={item.name}>{item.name}</option>)}</select></label><label className="text-[12px] font-medium text-[#555]">Section<select value={form.section} onChange={(event) => setForm({ ...form, section: event.target.value, subject: '' })} className={input} disabled={!selectedClass}><option value="">Select section</option>{(selectedClass?.sections || []).map((item) => <option key={item.name}>{item.name}</option>)}</select></label><label className="text-[12px] font-medium text-[#555]">Subject<select value={form.subject} onChange={(event) => setForm({ ...form, subject: event.target.value })} className={input} disabled={!form.section}><option value="">Select subject</option>{subjects.map((subject) => <option key={subject}>{subject}</option>)}</select></label><label className="text-[12px] font-medium text-[#555]">Teacher<select value={form.teacher_id} onChange={(event) => setForm({ ...form, teacher_id: event.target.value })} className={input}><option value="">Select teacher</option>{teachers.map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.name}{teacher.subject ? ` — ${teacher.subject}` : ''}</option>)}</select></label></div><div className="mt-6 flex justify-end"><Btn icon={Plus} onClick={save} disabled={saving}>{saving ? 'Assigning…' : 'Assign Teacher'}</Btn></div></Card></Layout>;
};

export const ViewAllocations = () => {
  const structure = useSchoolStructure(); const [rows, setRows] = useState([]); const [notice, setNotice] = useState(''); const [className, setClassName] = useState(''); const [section, setSection] = useState('');
  const load = useCallback(() => api.get('/teacher-allocations').then(({ data }) => setRows(data)).catch(() => setRows([])), []); useEffect(() => { load(); }, [load]); const remove = async (id) => { await api.delete(`/teacher-allocations/${id}`); setNotice('Allocation removed.'); load(); };
  const selectedClass = (structure.classes || []).find((item) => item.name === className); const sections = selectedClass?.sections || [];
  const filteredRows = useMemo(() => rows.filter((row) => (!className || row.class_name === className) && (!section || row.section === section)).sort((a, b) => a.teacher_name.localeCompare(b.teacher_name) || a.subject.localeCompare(b.subject)), [rows, className, section]);
  return <Layout><PageTitle title="View Allocations" subtitle="All assigned teachers are listed alphabetically. Filter only when you need a specific Class or Section." />{notice && <div className="mb-5 rounded-xl border border-green-100 bg-green-50 px-4 py-3 text-[13px] text-green-700">{notice}</div>}<Card title="Filter allocations" subtitle="Leave both fields as All to view every assigned teacher."><div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><label className="text-[12px] font-medium text-[#555]">Class<select value={className} onChange={(event) => { setClassName(event.target.value); setSection(''); }} className={input}><option value="">All Classes</option>{(structure.classes || []).map((item) => <option key={item.name}>{item.name}</option>)}</select></label><label className="text-[12px] font-medium text-[#555]">Section<select value={section} onChange={(event) => setSection(event.target.value)} className={input} disabled={!className}><option value="">All Sections</option>{sections.map((item) => <option key={item.name}>{item.name}</option>)}</select></label><div className="self-end text-[12px] text-[#777]">Showing <span className="font-semibold text-[#333]">{filteredRows.length}</span> allocation(s), ordered by teacher name.</div></div></Card><Card title="Assigned Teachers" subtitle="Alphabetical teacher list with their allocated class, section and subject." className="mt-5" pad="p-0"><div className="overflow-x-auto"><Table columns={[{ label: 'Teacher' }, { label: 'Class' }, { label: 'Section' }, { label: 'Subject' }, { label: 'Academic Year' }, { label: 'Action' }]}>{filteredRows.map((row) => <tr key={row.id} className="border-b border-gray-50"><td className="px-6 py-3 text-[13px] font-semibold">{row.teacher_name}</td><td className="py-3 text-[13px] text-[#666]">{row.class_name}</td><td className="py-3 text-[13px] text-[#666]">{row.section}</td><td className="py-3"><Badge color="blue">{row.subject}</Badge></td><td className="py-3 text-[13px] text-[#666]">{row.academic_year}</td><td className="py-3 pr-6"><button onClick={() => remove(row.id)} className="inline-flex items-center gap-1 text-[12px] font-semibold text-red-500"><Trash2 size={14} /> Remove</button></td></tr>)}</Table>{!filteredRows.length && <div className="py-12 text-center text-[13px] text-[#999]">No teacher allocations match these filters.</div>}</div></Card></Layout>;
};
